[package]
name = "repro-gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.15.2"
glib = "0.15.2"
gtk4 = "0.4.1"
